// SENDERS ACTIONS
export const SEND_MIDI_MESSAGE = 'SEND_MIDI_MESSAGE';
export const SEND_MIDI_OUT_DEVICE = 'SEND_MIDI_OUT_DEVICE';
export const SEND_MIDI_IN_DEVICE = 'SEND_MIDI_IN_DEVICE';
export const SEND_STATUS_MESSAGE = 'SEND_STATUS_MESSAGE';

// LAYOUT ACTIONS
export const HANDLE_EDITING_MODE = 'HANDLE_EDITING_MODE';
export const HANDLE_VISIBILITY_MODE = 'HANDLE_VISIBILITY_MODE';
export const EXIT_EDITING_MODE = 'EXIT_EDITING_MODE';
export const CREATE_BUTTON = 'CREATE_BUTTON';
export const CREATE_SLIDER = 'CREATE_SLIDER';
export const CREATE_LABEL = 'CREATE_LABEL';
export const CREATE_TAB = 'CREATE_TAB';
export const SET_CURRENT_TAB = 'SET_CURRENT_TAB';
export const LOCK_ELEMENT = 'LOCK_ELEMENT';
export const UPDATE_ELEMENT_POS = 'UPDATE_ELEMENT_POS';
export const UPDATE_ELEMENT_SIZE = 'UPDATE_ELEMENT_SIZE';
export const SAVE_LAYOUT = 'SAVE_LAYOUT';
export const RESET_BOARD = 'RESET_BOARD';
export const INIT_BOARD = 'INIT_BOARD';
export const INIT_BOARD_DONE = 'INIT_BOARD_DONE';
export const HANDLE_LOADING = 'HANDLE_LOADING';
export const HANDLE_CLOSE_DRAWER = 'HANDLE_CLOSE_DRAWER';
export const HANDLE_OPEN_DRAWER = 'HANDLE_OPEN_DRAWER';
export const EXIT_EDITING_ELEMENT = 'EXIT_EDITING_ELEMENT';
export const SAVE_ELEMENT_FORM = 'SAVE_ELEMENT_FORM';
export const SAVE_TAB_FORM = 'SAVE_TAB_FORM';
export const LOAD_ELEMENTS = 'LOAD_ELEMENTS';
export const LOAD_TABS = 'LOAD_TABS';
export const HANDLE_EDIT_TAB = 'HANDLE_EDIT_TAB';
export const HANDLE_EDIT_ELEMENT = 'HANDLE_EDIT_ELEMENT';
export const TAB_FORM_REQUEST = 'TAB_FORM_REQUEST';
export const ELEMENT_FORM_REQUEST = 'ELEMENT_FORM_REQUEST';
export const SET_INITIAL_TAB = 'SET_INITIAL_TAB';
export const SAVE_SETTINGS_FORM = 'SAVE_SETTINGS_FORM';
export const LOAD_SETTINGS = 'LOAD_SETTINGS';
export const DELETE_ELEMENT = 'DELETE_ELEMENT';
export const DELETE_TAB = 'DELETE_TAB';
export const DELETE_ELEMENTS_FROM_TAB = 'DELETE_ELEMENTS_FROM_TAB';
export const HANDLE_CONFIRMATION = 'HANDLE_CONFIRMATION';
export const SET_IP = 'SET_IP';

// IMPORT FROM BACKUP
export const IMPORT_FROM_BKP = 'IMPORT_FROM_BKP';
export const IMPORT_TABS_FROM_FILE = 'IMPORT_TABS_FROM_FILE';
export const IMPORT_ELEMENTS_FROM_FILE = 'IMPORT_ELEMENTS_FROM_FILE';
export const IMPORT_SETTINGS_FROM_FILE = 'IMPORT_SETTINGS_FROM_FILE';
